from genetic_algorithm.fitness_function.fitness_constants import MISSING_ACCOMP_FOR_MELODY_TICK, \
    EXCESS_ACCOMP_TICK_FOR_MELODY, TOO_BIG_CHORD_DROP, ACCOMP_TICK_NOT_BELOW_MELODY, DISSONANCE_INSIDE, \
    EMPTY_ACCOMPANIMENT


# fitness function

# enables for metrics

ENABLE_MISSING_ACCOMP_FOR_MELODY_TICK = True
ENABLE_EXCESS_ACCOMP_TICK_FOR_MELODY = True
ENABLE_TOO_BIG_CHORD_DROP = True
ENABLE_ACCOMP_TICK_NOT_BELOW_MELODY = True
ENABLE_DISSONANCE_INSIDE = True
ENABLE_DISSONANCE_WITH_MELODY = True
ENABLE_EMPTY_ACCOMPANIMENT = True

# definitions
TOO_BIG_CHORD_DROP_IN_NOTES = 13
# ALLOWED_ACCOMP_CHORDS_FOR_MELODY_KEY = {
#     (0, MAJOR_TONIC): [0, ]
# }

# awards
EVENT_TO_AWARD_WEIGHTS = {
    MISSING_ACCOMP_FOR_MELODY_TICK: -1,
    EXCESS_ACCOMP_TICK_FOR_MELODY: -10,
    TOO_BIG_CHORD_DROP: -20,
    ACCOMP_TICK_NOT_BELOW_MELODY: -5,
    DISSONANCE_INSIDE: 0,
    EMPTY_ACCOMPANIMENT: -1000,
    # DISSONANCE_WITH_MELODY: -3
}


# mutation

# definitions

MAX_MUTATION_SHIFT = 12


# note

# definitions

MAX_NOTE = 108
