from genetic_algorithm.fitness_function.fitness_constants import MISSING_ACCOMP_FOR_MELODY_TICK, \
    EXCESS_ACCOMP_TICK_FOR_MELODY, TOO_BIG_CHORD_DROP, ACCOMP_TICK_NOT_BELOW_MELODY, DISSONANCE_INSIDE, \
    EMPTY_ACCOMPANIMENT, DISSONANCE_WITH_MELODY, ACCOMPANIMENT_CHORD_EXISTS

# fitness function

# enables
from logging.logging_constants import WARNING_LEVEL, DEBUG_LEVEL

ENABLE_MISSING_ACCOMP_FOR_MELODY_TICK = True
ENABLE_EXCESS_ACCOMP_TICK_FOR_MELODY = True
ENABLE_TOO_BIG_CHORD_DROP = True
ENABLE_ACCOMP_TICK_NOT_BELOW_MELODY = True
ENABLE_DISSONANCE_INSIDE = True
ENABLE_DISSONANCE_WITH_MELODY = True
ENABLE_EMPTY_ACCOMPANIMENT = True
ENABLE_ACCOMPANIMENT_CHORD_EXISTS = True

# definitions
TOO_BIG_CHORD_DROP_IN_NOTES = 13
# ALLOWED_ACCOMP_CHORDS_FOR_MELODY_KEY = {
#     (0, MAJOR_TONIC): [0, ]
# }

# awards
EVENT_TO_AWARD_WEIGHTS = {
    MISSING_ACCOMP_FOR_MELODY_TICK: 2,
    EXCESS_ACCOMP_TICK_FOR_MELODY: 3,
    TOO_BIG_CHORD_DROP: 30,
    ACCOMP_TICK_NOT_BELOW_MELODY: 5,
    DISSONANCE_INSIDE: 0,
    EMPTY_ACCOMPANIMENT: 1000,
    DISSONANCE_WITH_MELODY: 3,
    ACCOMPANIMENT_CHORD_EXISTS: -1
}


# mutation

# definitions

MAX_MUTATION_SHIFT = 12


# note

# definitions

MAX_NOTE = 108


# logging

# enables

LOG_LEVEL = DEBUG_LEVEL
