from genetic_algorithm.fitness_function.fitness_constants import MISSING_ACCOMP_FOR_MELODY_TICK, \
    EXCESS_ACCOMP_TICK_FOR_MELODY, TOO_BIG_CHORD_DROP, ACCOMP_TICK_NOT_BELOW_MELODY, DISSONANCE_INSIDE, \
    EMPTY_ACCOMPANIMENT, DISSONANCE_WITH_MELODY, ACCOMPANIMENT_CHORD_EXISTS, TOO_WIDE_ACCOMPANIMENT_RANGE, \
    CORRECT_TRIAD_FOR_MELODY_KEY, CHORD_INCLUDE_MELODY_NOTE, COMPLETED_PROGRESSION, PARTIAL_PROGRESSION

# fitness function

# enables
from logging.logging_constants import WARNING_LEVEL, DEBUG_LEVEL
from music_interfaces.composition.composition_constants import MAJOR_TONIC, MINOR_TONIC, MAJOR_TRIAD, MINOR_TRIAD, \
    DIMINISHED_CHORD

ENABLE_MISSING_ACCOMP_FOR_MELODY_TICK = True
ENABLE_EXCESS_ACCOMP_TICK_FOR_MELODY = True
ENABLE_TOO_BIG_CHORD_DROP = True
ENABLE_ACCOMP_TICK_NOT_BELOW_MELODY = True
ENABLE_DISSONANCE_INSIDE = True
ENABLE_DISSONANCE_WITH_MELODY = True
ENABLE_EMPTY_ACCOMPANIMENT = True
ENABLE_ACCOMPANIMENT_CHORD_EXISTS = True
ENABLE_TOO_WIDE_ACCOMPANIMENT_RANGE = True
ENABLE_CORRECT_TRIAD_FOR_MELODY_KEY = True
ENABLE_CHORD_INCLUDE_MELODY_NOTE = True
ENABLE_COMPLETED_PROGRESSION = True
ENABLE_PARTIAL_PROGRESSION = True

# definitions
TOO_BIG_CHORD_DROP_IN_NOTES = 13
ALLOWED_ACCOMP_TRIADS_FOR_MELODY_TONIC = {
    MAJOR_TONIC: [[0 + note for note in MAJOR_TRIAD], [2 + note for note in MINOR_TRIAD],
                  [4 + note for note in MINOR_TRIAD], [5 + note for note in MAJOR_TRIAD],
                  [7 + note for note in MAJOR_TRIAD], [9 + note for note in MINOR_TRIAD],
                  [11 + note for note in DIMINISHED_CHORD]],
    MINOR_TONIC: [[0 + note for note in MINOR_TRIAD], [2 + note for note in DIMINISHED_CHORD],
                  [3 + note for note in MAJOR_TRIAD], [5 + note for note in MINOR_TRIAD],
                  [7 + note for note in MINOR_TRIAD], [8 + note for note in MAJOR_TRIAD],
                  [10 + note for note in MAJOR_TRIAD]]
}
TOO_WIDE_ACCOMPANIMENT_RANGE_IN_NOTES = 12

# awards
EVENT_TO_AWARD_WEIGHTS = {
    MISSING_ACCOMP_FOR_MELODY_TICK: 8,
    EXCESS_ACCOMP_TICK_FOR_MELODY: 4,
    TOO_BIG_CHORD_DROP: 10,
    ACCOMP_TICK_NOT_BELOW_MELODY: 20,
    DISSONANCE_INSIDE: 0,
    EMPTY_ACCOMPANIMENT: 10000,
    DISSONANCE_WITH_MELODY: 6,
    ACCOMPANIMENT_CHORD_EXISTS: -2,
    TOO_WIDE_ACCOMPANIMENT_RANGE: 10,
    CORRECT_TRIAD_FOR_MELODY_KEY: -9,
    CHORD_INCLUDE_MELODY_NOTE: -3,
    COMPLETED_PROGRESSION: -1,
    PARTIAL_PROGRESSION: -4,
}


# mutation

# definitions

MAX_MUTATION_SHIFT = 12


# note

# definitions

MAX_NOTE = 108


# logging

# enables

LOG_LEVEL = DEBUG_LEVEL
