# log level names
DEBUG_LEVEL = "DEBUG"
INFO_LEVEL = "INFO"
WARNING_LEVEL = "WARNING"
ERROR_LEVEL = "ERROR"

LOG_LEVEL_TO_ENABLED_LEVELS = {
    DEBUG_LEVEL: [DEBUG_LEVEL, INFO_LEVEL, WARNING_LEVEL, ERROR_LEVEL],
    INFO_LEVEL: [INFO_LEVEL, WARNING_LEVEL, ERROR_LEVEL],
    WARNING_LEVEL: [WARNING_LEVEL, ERROR_LEVEL],
    ERROR_LEVEL: [ERROR_LEVEL],
    None: []
}
