MAJOR_TONIC = "major"
MINOR_TONIC = "minor"
# please keep chords sorted
MAJOR_TRIAD = [0, 4, 7]
MINOR_TRIAD = [0, 3, 7]
MAJOR_TRIAD_1I = [0, 3, 8]
MAJOR_TRIAD_2I = [0, 5, 9]
MINOR_TRIAD_1I = [0, 4, 9]
MINOR_TRIAD_2I = [0, 5, 8]
DIMINISHED_CHORD = [0, 3, 6]
SUS2_CHORD = [0, 2, 7]
SUS4_CHORD = [0, 5, 7]
EMPTY_CHORD = []

MAJOR_TRIAD_NAME = "major_triad"
MINOR_TRIAD_NAME = "minor_triad"
MAJOR_TRIAD_1I_NAME = "major_triad_1i"
MAJOR_TRIAD_2I_NAME = "major_triad_2i"
MINOR_TRIAD_1I_NAME = "minor_triad_1i"
MINOR_TRIAD_2I_NAME = "minor_triad_2i"
DIMINISHED_CHORD_NAME = "diminished_chord"
SUS2_CHORD_NAME = "sus2_chord"
SUS4_CHORD_NAME = "sus4_chord"
EMPTY_CHORD_NAME = "empty_chord"
UNKNOWN_CHORD_NAME = "unknown_chord"

NAME_TO_CHORD = {
    MAJOR_TRIAD_NAME: MAJOR_TRIAD,
    MINOR_TRIAD_NAME: MINOR_TRIAD,
    MAJOR_TRIAD_1I_NAME: MAJOR_TRIAD_1I,
    MAJOR_TRIAD_2I_NAME: MAJOR_TRIAD_2I,
    MINOR_TRIAD_1I_NAME: MINOR_TRIAD_1I,
    MINOR_TRIAD_2I_NAME: MINOR_TRIAD_2I,
    DIMINISHED_CHORD_NAME: DIMINISHED_CHORD,
    SUS2_CHORD_NAME: SUS2_CHORD,
    SUS4_CHORD_NAME: SUS4_CHORD,
    EMPTY_CHORD_NAME: EMPTY_CHORD,
}

# progrssions took from https://en.wikipedia.org/wiki/List_of_chord_progressions
FIFTIES_PROGRESSION = [
    (0, MAJOR_TRIAD_NAME),
    (-3, MINOR_TRIAD_NAME),
    (-7, MAJOR_TRIAD_NAME),
    (-5, MAJOR_TRIAD_NAME)
]
I_V_VIM_IV_PROGRESSION = [
    (0, MAJOR_TRIAD_NAME),
    (-5, MAJOR_TRIAD_NAME),
    (-3, MINOR_TRIAD_NAME),
    (-7, MAJOR_TRIAD_NAME),
]
I_V_BVII_IV_PROGRESSION = [
    (0, MAJOR_TRIAD_NAME),
    (-5, MAJOR_TRIAD_NAME),
    (-2, MAJOR_TRIAD_NAME),
    (-7, MAJOR_TRIAD_NAME),
]
ANDALUSIAN_CADENCE_PROGRESSION = [
    (0, MINOR_TRIAD_NAME),
    (-2, MAJOR_TRIAD_NAME),
    (-4, MAJOR_TRIAD_NAME),
    (-5, MAJOR_TRIAD_NAME),
]
CIRCLE_PROGRESSION = [
    (0, MINOR_TRIAD_NAME),
    (-7, MINOR_TRIAD_NAME),
    (-2, MAJOR_TRIAD_NAME),
    (-9, MAJOR_TRIAD_NAME),
]
MONTGOMERY_WARD_BRIDGE_PROGRESSION = [
    (0, MAJOR_TRIAD_NAME),
    (-7, MAJOR_TRIAD_NAME),
    (2, MINOR_TRIAD_NAME),
    (-5, MAJOR_TRIAD_NAME),
]
I_VIM_IIM_V_PROGRESSION = [
    (0, MAJOR_TRIAD_NAME),
    (-3, MINOR_TRIAD_NAME),
    (-10, MINOR_TRIAD_NAME),
    (-5, MAJOR_TRIAD_NAME),
]
I_BVII_BVI_BVII_PROGRESSION = [
    (0, MAJOR_TRIAD_NAME),
    (-2, MAJOR_TRIAD_NAME),
    (-4, MAJOR_TRIAD_NAME),
    (-2, MAJOR_TRIAD_NAME),
]
PROGRESSIONS = [FIFTIES_PROGRESSION, I_V_VIM_IV_PROGRESSION, I_V_BVII_IV_PROGRESSION, ANDALUSIAN_CADENCE_PROGRESSION,
                CIRCLE_PROGRESSION, MONTGOMERY_WARD_BRIDGE_PROGRESSION, I_VIM_IIM_V_PROGRESSION,
                I_BVII_BVI_BVII_PROGRESSION]
